### ISSUE TITLE
connect A1M8 remote via tcp/ip

### ISSUE THREAD

**Issue by maggusscheppi** [husarion/rplidar-docker#2]
Is it possible to use a remote lidar, e.g. via ser2net?

How would be the yaml config for that? Something like this?

`services:

  rplidar:
    image: husarion/rplidar:humble
    restart: unless-stopped
    network_mode: host
    ipc: host
    devices:
      - ip:port`

kind regards, Markus

**Comment by delihus** [comment]
Hi @maggusscheppi!
[Sllidar library](https://github.com/husarion/sllidar_ros2.git) supports only serial port devices. 

Best regards!
JD
